In [1]:
import numpy as np
import math

In [2]:
zero_state = np.array([[1, 0]]).T
zero_state

array([[1],
       [0]])

In [3]:
H = (1/math.sqrt(2)) * (np.array([[1, 1], [1, -1]]))
H

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [4]:
multi = np.dot(H, zero_state)
multi

array([[0.70710678],
       [0.70710678]])